---
- name: 'Upload secret in Hashi Vault'
  gather_facts: false
  hosts: 'localhost'
  tasks:
    - name: 'Print value (debug-only)'
      ansible.builtin.debug:
        msg: |
          Name: "{{ input_name }}"
          Secret: {{ input_secret }}
      when: vault_debug | bool

    - name: "Store {{ input_name }} in the project's Vault"
      community.hashi_vault.vault_write:
        url: "{{ ansible_hashi_vault_url }}"
        path: "{{ ansible_hashi_vault_engine_mount_point }}/data/{{ input_name }}"
        auth_method: "{{ ansible_hashi_vault_auth_method }}"
        role_id: "{{ ansible_hashi_vault_role_id }}"
        secret_id: "{{ ansible_hashi_vault_secret_id }}"
        data:
          data:
            value: "{{ input_secret }}"
      no_log: "{{ not vault_debug | bool }}"
